---
name: env-setup
description: Setup environment

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      if: matrix.os == 'ubuntu-latest'
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: matrix.os == 'ubuntu-latest'
      uses: docker/setup-buildx-action@v3

    - uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install poetry and dependencies
      run: |
        pip3 install --no-cache-dir --upgrade pip poetry
        poetry install --no-interaction
      shell: "bash"
